version: '2'

services:
  idrac:
    image: t4cc0re/idrac6
    build: .
    restart: always
    ports:
      - 5800:5800
    environment:
      - IDRAC_HOST=idrac1.example.com
      - IDRAC_USER=root
      - IDRAC_PASSWORD=1234
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
